# Generated by Django 3.2 on 2021-07-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30, verbose_name='网站分组')),
            ],
            options={
                'verbose_name': '网站分组选择表',
                'verbose_name_plural': '网站分组选择表',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='PartChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=30, verbose_name='网站分区')),
            ],
            options={
                'verbose_name': '网站分区选择表',
                'verbose_name_plural': '网站分区选择表',
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('title', models.CharField(max_length=50, verbose_name='网站标题')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='网站介绍')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('site_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.groupchoice')),
            ],
            options={
                'verbose_name': '网站信息表',
                'verbose_name_plural': '网站信息表',
                'db_table': 'site',
            },
        ),
        migrations.AddField(
            model_name='groupchoice',
            name='group_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.partchoice'),
        ),
    ]
