# Generated by Django 3.2 on 2021-07-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchoice',
            options={'verbose_name': '网站分组', 'verbose_name_plural': '网站分组'},
        ),
        migrations.AlterModelOptions(
            name='partchoice',
            options={'verbose_name': '网站分区', 'verbose_name_plural': '网站分区'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '网站信息', 'verbose_name_plural': '网站信息'},
        ),
    ]
